name: Generate HTML from Markdown

on:
  push:
    branches:
      - main  # 监听 main 分支的推送

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Convert Markdown to HTML
      run: |
        mkdir -p public/posts
        for file in _posts/*.md; do
          pandoc "$file" -o "public/posts/$(basename "${file%.*}").html"
        done

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add public/posts
        git commit -m "Generate HTML from Markdown"
        git push origin main