name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 或者你的默认分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Convert Markdown to HTML
      run: |
        mkdir -p posts
        for file in _posts/*.md; do
          pandoc "$file" -o "posts/$(basename "${file%.*}").html"
        done

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./  # 部署整个项目目录